[package]
name = "m5-core2-hello-idf"
version = "0.1.0"
authors = ["ronron-gh <motohiro.sanpei@gmail.com>"]
edition = "2021"
resolver = "2"
rust-version = "1.82"

[[bin]]
name = "m5-core2-hello-idf"
harness = false # do not use the built-in cargo test harness -> resolve rust-analyzer errors

[profile.release]
opt-level = "s"

[profile.dev]
debug = true    # Symbols are nice, and they don't increase the size on Flash
opt-level = "z"

[dependencies]
log = "0.4"
esp-idf-svc = { version = "0.52.1", features = ["critical-section", "embassy-time-driver", "embassy-sync"] }
# Remove `generic-queue-8` if you plan to use `embassy-time` WITH `embassy-executor`
embassy-time = { version = "0.5", features = ["generic-queue-8"] }

esp-idf-sys = { version = "0.37.2", features = ["binstart"] }
esp-idf-hal = "0.46.2"
anyhow = "1.0.104"

mipidsi = "0.6.0"
display-interface-spi = "0.4.1"
embedded-graphics = "0.7.1"
embedded-hal = "1"
axp192 = "0.2.0"

[build-dependencies]
embuild = "0.33"
